PRAGMA foreign_keys = ON;

CREATE TABLE USERS(
    username VARCHAR(20) NOT NULL,
    password VARCHAR(20) NOT NULL,
    profilepath VARCHAR(100) NOT NULL,
    PRIMARY KEY(username)
);

CREATE TABLE RESUME(
    owner VARCHAR(20) NOT NULL,
    filename VARCHAR(100) NOT NULL,
    created DATETIME,
    resid INTEGER PRIMARY KEY AUTOINCREMENT,
    FOREIGN KEY (owner) REFERENCES users
    ON DELETE CASCADE
);

CREATE TABLE TEMPLATE(
    imgfile VARCHAR(100) NOT NULL,
    templatefile VARCHAR(100) NOT NULL,
    templateid INTEGER PRIMARY KEY AUTOINCREMENT
);